name: "Deploy to netlify"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    name: "Deploy to Netlify"
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i

      - run: npm run build

      - uses: jsmrcaga/action-netlify-deploy@v2.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.MY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist
